// AUTO-GENERATED BY @sidebase/nuxt-auth
import { RouteOptions } from 'C:/Users/huber/Documents/ILA/auth-module/runtime/types.ts'
declare module 'nitropack' {
  interface NitroRouteRules {
    auth?: RouteOptions
  }
  interface NitroRouteConfig {
    auth?: RouteOptions
  }
}
