// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('C:/Users/huber/Documents/ILA/auth-module/runtime/server/services')
}
