// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../app/app.config";
import type { default as appConfig1 } from "../../node_modules/.pnpm/@nuxt+ui-pro@1.4.1_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@_tt7arnqqe5q243ukqqnqzywteu/node_modules/@nuxt/ui-pro/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}