// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/revive-payload.client.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/head/runtime/plugins/unhead.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/pages/runtime/plugins/router.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-site-config@2.2.15_magicast@0.3.5_rollup@4.21.1_vite@5.4.2_@types+node@22.5.0_terser@5.3_ca5lelmzgjm4wyovwt5jigmdca/node_modules/nuxt-site-config/dist/runtime/nuxt/plugins/0.siteConfig.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/revive-payload.server.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.4.1_rollup@4.21.1_vite@5.4.2_@types+node@22.5.0_terser@5.31.6_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.4.1_rollup@4.21.1_vite@5.4.2_@types+node@22.5.0_terser@5.31.6_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js").default> &
  InjectionType<typeof import("../../auth-module/runtime/plugin").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.65_magicast@0.3.5_rollup@4.21.1_vite@5.4.2_@types+node@22.5.0_terser@5_z7yu2yvmdfq2a5ja2tlgwv2zci/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/og-image-canonical-urls.server.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@3.0.0-rc.65_magicast@0.3.5_rollup@4.21.1_vite@5.4.2_@types+node@22.5.0_terser@5_z7yu2yvmdfq2a5ja2tlgwv2zci/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/route-rule-og-image.server.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.18.4_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@5.5_m4gdnsded2uvxqakmlevu2gvqa/node_modules/@nuxt/ui/dist/runtime/plugins/slideovers.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.18.4_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@5.5_m4gdnsded2uvxqakmlevu2gvqa/node_modules/@nuxt/ui/dist/runtime/plugins/modals.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.18.4_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@5.5_m4gdnsded2uvxqakmlevu2gvqa/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.4.4_magicast@0.3.5_rollup@4.21.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.4.4_magicast@0.3.5_rollup@4.21.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.4.10_magicast@0.3.5_rollup@4.21.1_vite@5.4.2_@types+node@22.5.0_terser@5.31.6__vue@3.4.38_typescript@5.5.4_/node_modules/@nuxt/icon/dist/runtime/plugin.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+content@2.13.2_ioredis@5.4.1_magicast@0.3.5_nuxt@3.13.0_@parcel+watcher@2.4.1_@types+no_7mce23clxcsf7jh55pnekac57q/node_modules/@nuxt/content/dist/runtime/plugins/ws.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui-pro@1.4.1_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@_tt7arnqqe5q243ukqqnqzywteu/node_modules/@nuxt/ui-pro/modules/pro/runtime/plugins/scrollbars.client").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/dev-server-logs.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@22.5.0_better-sqlite3@11.2.1_drizzle-orm@0.33.0_ob77ehyr3joxkudxgnhru2f57y/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui-pro@1.4.1_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@_tt7arnqqe5q243ukqqnqzywteu/node_modules/@nuxt/ui-pro/plugins/presets").default> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui-pro@1.4.1_magicast@0.3.5_rollup@4.21.1_ts-node@10.9.2_@types+node@22.5.0_typescript@_tt7arnqqe5q243ukqqnqzywteu/node_modules/@nuxt/ui-pro/plugins/variables").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
